### ISSUE TITLE
window_size = -1 gives error

### ISSUE THREAD

**Issue by maylad31** [ashawkey/ddddsr#1]
when i give window size 256 or 416 it is fine but when i give -1 it gives an error

**Comment by ashawkey** [comment]
With a 1920x1080 png I cannot reproduce the error, can you give more details? (e.g., OOM, or runtime error)

**Comment by maylad31** [comment]
Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Add node. Name:'Add_20' Status Message: Add_20: left operand cannot broadcast on dim 3 LeftShape: {1,64,972,972}, RightShape: {1,64,973,973}

By the way thanks for the code! Also it happens with gpu mostly.

**Comment by ashawkey** [comment]
@maylad31 Thanks for spotting the bug! I have fixed it. and you can upgrade to 0.1.6 to test.
